name: Update Homebrew Cask

on:
  schedule:
    # Runs daily at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  update-cask:
    runs-on: macos-latest
    steps:
      - name: Check out your tap repository
        uses: actions/checkout@v4
      - name: Run update.sh
        run: sh update.sh
